# Generated by Django 5.2.3 on 2025-06-27 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Departamento', models.CharField(choices=[('LP', 'La Paz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('CB', 'Cochabamba'), ('CH', 'Chuquisaca'), ('SC', 'Santa Cruz'), ('TJ', 'Tarija'), ('BE', 'Beni'), ('PA', 'Pando')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CUERDA_ANDINA', 'Cuerda andina'), ('VIENTO_ANDINO', 'Viento andino'), ('PERCUSION_FOLKLORICA', 'Percusión folklórica'), ('TECLADO_POPULAR', 'Teclado popular'), ('ELECTRONICO_FUSION', 'Electrónico fusión'), ('AUTOCTONO', 'Autóctono ceremonial')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agrupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Instrumentos', models.ManyToManyField(related_name='agrupaciones', to='musica.instrumentos')),
            ],
        ),
        migrations.CreateModel(
            name='Ritmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('instrumentos', models.ManyToManyField(related_name='ritmos', to='musica.instrumentos')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('agrupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.agrupacion')),
                ('instrumentos', models.ManyToManyField(blank=True, to='musica.instrumentos')),
                ('ritmos', models.ManyToManyField(blank=True, to='musica.ritmo')),
            ],
        ),
        migrations.AddField(
            model_name='agrupacion',
            name='Ritmo',
            field=models.ManyToManyField(related_name='agrupaciones', to='musica.ritmo'),
        ),
    ]
