# Generated by Django 5.2.3 on 2025-06-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agrupacion',
            name='Instrumentos',
        ),
        migrations.RemoveField(
            model_name='agrupacion',
            name='Ritmo',
        ),
        migrations.AddField(
            model_name='agrupacion',
            name='descripcion',
            field=models.TextField(default='', help_text='Descripción breve del grupo o artista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agrupacion',
            name='tipo',
            field=models.CharField(choices=[('SOLISTA', 'Solista'), ('GRUPAL', 'Grupal'), ('DUO', 'Dúo')], default='GRUPAL', help_text='Tipo de agrupación: solista, grupal o dúo', max_length=10),
        ),
    ]
