# Generated by Django 5.2.3 on 2025-06-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_remove_agrupacion_instrumentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='Departamento',
        ),
        migrations.AddField(
            model_name='departamento',
            name='ubicacion',
            field=models.CharField(choices=[('Sur', 'Sur'), ('Occidente', 'Occidente'), ('Oriente', 'Oriente'), ('Centro', 'Centro'), ('Norte', 'Norte')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
