# Generated by Django 5.2.3 on 2025-06-27 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_remove_departamento_departamento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrumentos',
            new_name='Instrumento',
        ),
        migrations.RenameField(
            model_name='cancion',
            old_name='instrumentos',
            new_name='instrumento',
        ),
        migrations.RenameField(
            model_name='ritmo',
            old_name='instrumentos',
            new_name='instrumento',
        ),
    ]
